export const LOADING_GLOBAL_SHOW = 'LOADING_GLOBAL_SHOW'
export const LOADING_GLOBAL_HIDE = 'LOADING_GLOBAL_HIDE'
export const LOADING_COMPONENT_SHOW = 'LOADING_COMPONENT_SHOW'
export const LOADING_COMPONENT_HIDE = 'LOADING_COMPONENT_HIDE'
export const RENDER_PAGE_SHOW = 'RENDER_PAGE_SHOW'
export const RENDER_PAGE_HIDE = 'RENDER_PAGE_HIDE'


